id: PD52692C3
initial_creation_type: input
source_metadata:
  Title: Mahāyāna-sūtra-saṃgrahaḥ ( part 1)
  Editor: Vaidya, P.L
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1961'
  Jetavanavihāravarṇanaṃ prathamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Avīciśoṣaṇaṃ nāma dvitīyaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Sattvadhātuparimokṣaṇaṃ tṛtīyaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Candrādyutpattirnāma caturthaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Vividharaśminiḥsaraṇaṃ pañcamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tathāgatasaṃvādaḥ ṣaṣṭhaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Avalokiteśvarapuṇyaskandhakathanaṃ saptamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Vaineyadharmopadeśaḥ aṣṭamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Asurāśvāsanaṃ navamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Kāñcanamayabhūmyādyupasthānaṃ daśamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  balisamāśvāsanamekādaśamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Yakṣādisamāśvāsanaṃ dvādaśaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Devabhavanabhramaṇaṃ trayodaśaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Siṃhalabhramaṇaṃ caturdaśaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Vārāṇasībhramaṇaṃ pañcadaśaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Magadhabhramaṇaṃ ṣoḍaśaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīyo nirvyūhaḥ - aśvarājavarṇanaṃ prathamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Romavivaraṇāvarṇanaṃ dvitīyaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣaḍakṣarīmahāvidyāmāhātmyavarṇanaṃ tṛtīyaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣaḍakṣarimahāvidyāmaṇḍalavarṇanaṃ caturthaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Mahāvidyopadeśo nāma pañcamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Mahāvidyāmaṇḍalavarṇanaṃ ṣaṣṭhaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aṣṭamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:03:28.921380'
last_modified_at: '2022-03-08T16:03:28.921395'
